<a href="https://colab.research.google.com/github/Lydia-Sanchez-Cano/APRENDIZAJE_AUTOMATICO_23_24/blob/main/0%20INTRODUCCION/0.3.%20Vectores%20y%20matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
lista = [5,6,9,8,7,4,65,2,2,56,46,54]
print(lista)

[5, 6, 9, 8, 7, 4, 65, 2, 2, 56, 46, 54]


In [2]:
2 in lista

True

In [3]:
35 in lista

False

In [4]:
lista[0]

5

In [5]:
lista[-1]

54

In [6]:
lista[2:4]

[9, 8]

In [7]:
lista[:5]

[5, 6, 9, 8, 7]

In [8]:
lista[4:]

[7, 4, 65, 2, 2, 56, 46, 54]

In [9]:
lista[:]

[5, 6, 9, 8, 7, 4, 65, 2, 2, 56, 46, 54]

In [10]:
import numpy as np

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,10,2)


array([1, 3, 5, 7, 9])

In [12]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [13]:
len(a)

4

In [14]:
min(a)

1

In [15]:
max(a)

4

In [16]:
b = np.array([[1,2,3],[5,6,4],[7,5,2]])
b

array([[1, 2, 3],
       [5, 6, 4],
       [7, 5, 2]])

In [17]:
b[0]

array([1, 2, 3])

In [18]:
b[:,1]

array([2, 6, 5])

In [19]:
b[2,2]

2

# Revisar la indexación de matrices (filas columnas)

In [20]:
b[0:2, 1:3]

array([[2, 3],
       [6, 4]])

In [21]:
a = np.random.rand(5,5)
a

array([[0.7048867 , 0.85641784, 0.60474024, 0.3977683 , 0.72813704],
       [0.9993474 , 0.96017511, 0.34600574, 0.6618093 , 0.6817151 ],
       [0.68934703, 0.61858766, 0.67993836, 0.31605765, 0.07025033],
       [0.34984363, 0.71629643, 0.67785654, 0.27957671, 0.78293022],
       [0.00837433, 0.37834085, 0.99204952, 0.51479847, 0.45006549]])

In [22]:
a.shape

(5, 5)

In [23]:
b  = np.random.rand(5,5)
b

array([[0.21701958, 0.72022522, 0.19460226, 0.62784198, 0.78037049],
       [0.17654403, 0.73956366, 0.18622198, 0.11938478, 0.67394514],
       [0.2926804 , 0.08029225, 0.79084447, 0.74603373, 0.16071041],
       [0.41545759, 0.79090876, 0.12558001, 0.01828267, 0.24276609],
       [0.85552566, 0.40324987, 0.61648278, 0.79207795, 0.15190496]])

In [24]:
a + b

array([[0.92190628, 1.57664306, 0.7993425 , 1.02561028, 1.50850753],
       [1.17589143, 1.69973877, 0.53222772, 0.78119408, 1.35566024],
       [0.98202743, 0.69887991, 1.47078283, 1.06209138, 0.23096074],
       [0.76530122, 1.5072052 , 0.80343655, 0.29785938, 1.02569631],
       [0.86389999, 0.78159072, 1.6085323 , 1.30687642, 0.60197044]])

In [25]:
a-b

array([[ 0.48786712,  0.13619262,  0.41013798, -0.23007368, -0.05223345],
       [ 0.82280338,  0.22061145,  0.15978376,  0.54242453,  0.00776997],
       [ 0.39666663,  0.53829541, -0.11090611, -0.42997607, -0.09046008],
       [-0.06561397, -0.07461233,  0.55227653,  0.26129403,  0.54016413],
       [-0.84715132, -0.02490901,  0.37556674, -0.27727948,  0.29816053]])

In [26]:
a*b

array([[0.15297421, 0.61681372, 0.11768382, 0.24973564, 0.56821666],
       [0.17642881, 0.71011062, 0.06443388, 0.07900996, 0.45943858],
       [0.20175837, 0.0496678 , 0.53772549, 0.23578967, 0.01128996],
       [0.14534519, 0.56652513, 0.08512523, 0.00511141, 0.19006891],
       [0.00716446, 0.1525659 , 0.61158145, 0.40776052, 0.06836718]])

In [27]:
a/b

array([[3.24803275e+00, 1.18909727e+00, 3.10757043e+00, 6.33548433e-01,
        9.33065834e-01],
       [5.66061300e+00, 1.29829948e+00, 1.85802844e+00, 5.54349831e+00,
        1.01152908e+00],
       [2.35528933e+00, 7.70420106e+00, 8.59762421e-01, 4.23650625e-01,
        4.37123721e-01],
       [8.42068200e-01, 9.05662530e-01, 5.39780591e+00, 1.52918960e+01,
        3.22503948e+00],
       [9.78852255e-03, 9.38229330e-01, 1.60920881e+00, 6.49934105e-01,
        2.96280977e+00]])

In [28]:
np.transpose(a)

array([[0.7048867 , 0.9993474 , 0.68934703, 0.34984363, 0.00837433],
       [0.85641784, 0.96017511, 0.61858766, 0.71629643, 0.37834085],
       [0.60474024, 0.34600574, 0.67993836, 0.67785654, 0.99204952],
       [0.3977683 , 0.6618093 , 0.31605765, 0.27957671, 0.51479847],
       [0.72813704, 0.6817151 , 0.07025033, 0.78293022, 0.45006549]])

In [29]:
1/a

array([[  1.41866771,   1.16765433,   1.65360255,   2.51402636,
          1.37336785],
       [  1.00065302,   1.04147669,   2.89012546,   1.51100928,
          1.46688843],
       [  1.45064816,   1.61658575,   1.47072155,   3.16397969,
         14.23480823],
       [  2.85841993,   1.39607005,   1.47523841,   3.57683591,
          1.27725303],
       [119.41250717,   2.64311928,   1.00801419,   1.9425077 ,
          2.22189888]])

## PROBLEMAS

1. Escribe una función **suma_matrices** que tome dos matrices **NumPy** como argumentos y devuelva una nueva matriz que sea la suma de las dos matrices originales. No utilices la operación de suma incorporada de NumPy (+).

In [35]:
import numpy as np

def suma_matrices(A, B):
  # INTRODUCIR EL CÓDIGO DE LA FUNCIÓN AQUÍ
  # VALIDA QUE LAS MATRICES DE ENTRADA TIENEN LA MISMA DIMENSIÓN
  # Obtiene las dimensiones de las matrices
  filas, columnas = A.shape

  # Verifica si las matrices tienen las mismas dimensiones
  if A.shape != B.shape:
      raise ValueError("Las matrices deben tener las mismas dimensiones para ser sumadas")

  # Crea una nueva matriz para el resultado con las mismas dimensiones
  resultado = np.zeros((filas, columnas), dtype=A.dtype)

  # Realiza la suma de matrices utilizando bucles
  for i in range(filas):
      for j in range(columnas):
          resultado[i][j] = A[i][j] + B[i][j]

  return resultado
# Pruebas
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
assert np.array_equal(suma_matrices(A, B), np.array([[6, 8], [10, 12]]))

2. Escribe una función **transpuesta** que tome una matriz **NumPy** como argumento y **devuelva su transpuesta**. No utilices la propiedad T de NumPy.

In [33]:
import numpy as np

def transpuesta(A):
  # INTRODUCIR EL CÓDIGO DE LA FUNCIÓN AQUÍ
    filas, columnas = A.shape
    # Crea una nueva matriz para la transpuesta con las dimensiones invertidas
    transpuesta = np.zeros((columnas, filas), dtype=A.dtype)
    # Calcula la transpuesta utilizando bucles
    for i in range(filas):
        for j in range(columnas):
            transpuesta[j][i] = A[i][j]
    return transpuesta

# Pruebas
A = np.array([[1, 2, 3], [4, 5, 6]])
assert np.array_equal(transpuesta(A), np.array([[1, 4], [2, 5], [3, 6]]))

3. Escribe una función **multiplicar_matrices** que tome dos matrices **NumPy** como argumentos y devuelva una nueva matriz que sea el resultado de la multiplicación de las dos matrices originales. No utilices la operación de multiplicación de matrices incorporada de NumPy (@ o np.dot).

In [34]:
import numpy as np

def multiplicar_matrices(A, B):
  # INTRODUCIR EL CÓDIGO DE LA FUNCIÓN AQUÍ
  # VALIDA QUE LAS MATRICES DE ENTRADA TIENEN LAS DIMENSIONES
  # ADECUADAS QUE PERMITEN LA MULTIPLICACIÓN MATRICIAL
  # Obtiene las dimensiones de las matrices
    filas1, columnas1 = A.shape
    filas2, columnas2 = B.shape

    # Verifica si las matrices son multiplicables
    if columnas1 != filas2:
        raise ValueError("Las matrices no son multiplicables")

    # Crea una nueva matriz para el resultado con las dimensiones adecuadas
    resultado = np.zeros((filas1, columnas2), dtype=A.dtype)

    # Realiza la multiplicación de matrices utilizando bucles
    for i in range(filas1):
        for j in range(columnas2):
            for k in range(columnas1):
                resultado[i][j] += A[i][k] * B[k][j]

    return resultado

# Pruebas
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])
assert np.array_equal(multiplicar_matrices(A, B), np.array([[4, 4], [10, 8]]))